behaviors:
  PlayerContinuous:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 64000
      buffer_init_steps: 2000
      tau: 0.005
      steps_per_update: 100
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 11
    checkpoint_interval: 50000
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true